.ORIG x3000
;KB Polling Routine
KPOLL 	LDI R1, KBSR_ADDR
     	BRzp KPOLL
     	LDI R0, KBDR_ADDR
;Display Polling Routine
DPOLL	LDI R1, DSR_ADDR
	BRzp DPOLL
	STI R0, DDR_ADDR
HALT

KBSR_ADDR .FILL xFE00
KBDR_ADDR .FILL xFE02
DSR_ADDR  .FILL xFE04
DDR_ADDR  .FILL xFE06
.END
